apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdepl1
  labels:
    app: pythontest1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythontest1
  template:
    metadata:
      labels:
        app: pythontest1
    spec:
      containers:
      - name: app
        image: leo1-nuci3:5000/pythontest1:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
