hosts: all
vars:
  mykey_path: "~/.ssh/id_rsa.pub"
tasks:
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_files:
    - mykey_path
